name: ChatPlugin
version: 1.0.0
main: org.Denis496.chatPlugin.ChatPlugin
api-version: '1.21'
author: Denis496
description: Advanced chat plugin with local/global channels, mentions, and more!
softdepend: [LuckPerms, Teams, Marks, WarnsPlugin, PlayTimeTracker]

commands:
  message:
    description: Send a private message to a player
    usage: /<command> <player> <message>
    aliases: [m, msg, tell, whisper, w]
    permission: chat.command.message

  reply:
    description: Reply to your last private message
    usage: /<command> <message>
    aliases: [r]
    permission: chat.command.reply

  roll:
    description: Roll a dice
    usage: /<command> [number]
    permission: chat.command.roll

  coin:
    description: Flip a coin
    usage: /<command>
    permission: chat.command.coin

  chatplugin:
    description: Main plugin command
    usage: /<command> [reload]
    permission: chat.admin

  chatformat:
    description: Manage chat formats
    usage: /<command> [preview|set|reset|info]
    permission: chat.admin.format

  muteinfo:
    description: Check your mute status
    usage: /<command>
    permission: chat.command.muteinfo

  local:
    description: Switch to local chat mode
    usage: /<command>
    permission: chat.command.local
    aliases: [l]

  global:
    description: Switch to global chat mode
    usage: /<command>
    permission: chat.command.global
    aliases: [g]

  dm:
    description: Toggle direct messages
    usage: /<command> <on|off>
    permission: chat.command.dm

  ignore:
    description: Ignore or unignore a player
    usage: /<command> <player|list>
    permission: chat.command.ignore

permissions:
  chat.local:
    description: Send messages in local chat
    default: true

  chat.global:
    description: Send messages in global chat
    default: true

  chat.mention:
    description: Mention players with @
    default: true

  chat.bypass.antispam:
    description: Bypass anti-spam restrictions
    default: op

  chat.bypass.ignore:
    description: Cannot be ignored by other players
    default: op

  chat.command.message:
    description: Use /message and its aliases
    default: true

  chat.command.reply:
    description: Use /reply command
    default: true

  chat.command.roll:
    description: Use /roll command
    default: true

  chat.command.coin:
    description: Use /coin command
    default: true

  chat.command.muteinfo:
    description: Check mute status
    default: true

  chat.command.local:
    description: Use /local command
    default: true

  chat.command.global:
    description: Use /global command
    default: true

  chat.command.dm:
    description: Use /dm command
    default: true

  chat.command.ignore:
    description: Use /ignore command
    default: true

  chat.proxy:
    description: Send messages through proxy
    default: true

  chat.admin:
    description: Access admin configuration commands
    default: op

  chat.admin.format:
    description: Access chat format commands
    default: op

  chat.*:
    description: All chat permissions
    default: op
    children:
      chat.local: true
      chat.global: true
      chat.mention: true
      chat.bypass.antispam: true
      chat.bypass.ignore: true
      chat.command.message: true
      chat.command.reply: true
      chat.command.roll: true
      chat.command.coin: true
      chat.command.muteinfo: true
      chat.command.local: true
      chat.command.global: true
      chat.command.dm: true
      chat.command.ignore: true
      chat.proxy: true
      chat.admin: true
      chat.admin.format: true